server:
  port: 8071
spring:
  mvc:
    problemdetails:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

management:
  tracing:
    enabled: false

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    io.github.susimsek.springaisamples: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
weather:
  client:
    api-key: ${WEATHER_API_KEY}
    api-url: http://api.weatherapi.com/v1
