server:
  port: 8071
spring:
  mvc:
    problemdetails:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


management:
  tracing:
    enabled: false

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    io.github.susimsek.springaisamples: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  http:
    enabled: true
    level: FULL
    obfuscate:
      enabled: true
      mask-value: "****"
      headers:
        - Authorization
        - Cookie
        - Set-Cookie
        - X-API-Key
        - X-CSRF-Token
        - WWW-Authenticate
        - X-JWS-Signature
      parameters:
        - key
        - password
        - token
        - secret
        - api_key
        - access_token
        - refresh_token
      json-body-fields:
        - $.title
        - $.token
        - $.accessToken
        - $.refreshToken
        - $.idToken
        - $.email
        - $.secretKey
        - $.apiSecret
        - $.apiKey
    exclude:
      rules:
        - path-pattern: "/actuator/**"
        - pathPattern: "/error"
        - pathPattern: "/static/**"
        - pathPattern: "/public/**"
        - pathPattern: "/resources/**"
        - pathPattern: "/css/**"
        - pathPattern: "/js/**"
        - path-pattern: "/images/**"
        - path-pattern: "/favicon.ico"
        - pathPattern: "/webjars/**"
        - pathPattern: "/v3/api-docs/**"
        - pathPattern: "/swagger-ui/**"
        - pathPattern: "/api-docs/**"
    include:
      rules:
        - pathPattern: "/**"
weather:
  client:
    api-key: ${WEATHER_API_KEY}
    api-url: http://api.weatherapi.com/v1

security:
  content-security-policy: "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://cdn.redoc.ly; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com https://cdnjs.cloudflare.com; worker-src 'self' blob:; img-src 'self' https://avatars.githubusercontent.com data: https://cdn.redoc.ly; frame-src 'self' data:; font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com data:"
  jwt:
    issuer: localhost
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvjmNBc/Yzx2gFZmd6DhCoSUf1BnlIczVR7lxKJwCla6n9tIj3x6YXIwvZgjIb2A1I2CaqBIy7Ud6eUILJ3PHwuXGCOBCOcX7xm/a95A3NTEZKpNDNHpIISh6FF9rSR3+D52+LOuDO2kL9/aE5hwFkPk4Z/DLA8+cxuFIGuSJXStuGM6MG1vtpStKdzdt8EE+1l1vNmnpkiBnMWYZEBkmflyZB7/C53zcRttdtNBOPOHktfvEWR2JwSYctnqNXU+eE4VvVIWBvY/HhzURzAQst6GPLF7pKDjg8wpN4Dn/eSDhg7A4S9tUVPCFYzK+c+4M75ZAk31dXEkBw7nuCdEYLwIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC+OY0Fz9jPHaAVmZ3oOEKhJR/UGeUhzNVHuXEonAKVrqf20iPfHphcjC9mCMhvYDUjYJqoEjLtR3p5Qgsnc8fC5cYI4EI5xfvGb9r3kDc1MRkqk0M0ekghKHoUX2tJHf4Pnb4s64M7aQv39oTmHAWQ+Thn8MsDz5zG4Uga5IldK24YzowbW+2lK0p3N23wQT7WXW82aemSIGcxZhkQGSZ+XJkHv8LnfNxG21200E484eS1+8RZHYnBJhy2eo1dT54ThW9UhYG9j8eHNRHMBCy3oY8sXukoOODzCk3gOf95IOGDsDhL21RU8IVjMr5z7gzvlkCTfV1cSQHDue4J0RgvAgMBAAECggEAGGGoAaayU1mouxwFcU5EvALWIYlwJPTsIVVTe7EDY8wPG0Oz9VUmkjYlnR5jEmNybCZlrEUo4eDXgdNFOrlMUV7CE0ErO9x0eOq9Vh3V9atlXl+hrYg+1oEppJLWXXjKp5XAWmGVYHgGYLHoNtZAoGRRJoFmhAaIQbV+WHQSZy6A6PtcpKFPAdUC+65AIBYi1gSysoFlVVCVSPSPtFMLOLCknHe3vsT5AMmYfQMiAgIE+UQqeK3IdIZ4nSSkRn+cJjjm6gBALEwuAASnGTpGHJve4PRq1fhp9Qxji7+irTOQDS/zKx54QEZ210lHQlt4WQUBpqyDlsYwISPhT2wggQKBgQD4EZ9P88B1PiqO9U6QrLxJuO80UIfr99SoAZm/dYiw9aXmPrwkdzKwQ2gGz+wsane74m+MoTj6UpPLtMtpLgK/VaGzYI+ueQ6t0sBLOhnQKlXHf3JclrOoYko01EyZJPY39pZvYYTg/IzY8tXl7HLcHa2X+cf6WKuJ3sh5j/IQkwKBgQDETn2R+dVi2fVe1re+G1gB6QaW1qRPzkpy09Nmf6lXboIeJkLhiEh44bnC8bPjQAGYooHdHgqPXI/3LK2ioE86PIQ/hYo9L6XYetYVJCjMAcbMKSqa4WQQqHNHnCpmbNhWohF8BZgtKpehx6SR9RzBBLOrqGSd6nLVyA0ssgaHdQKBgQCUx6zu/Nhu+Ov5dbK7Hn6HEL2WeL4sjiUi5mLZ65oh2BK59uJMVJk4EhVwEIArW2eYbgRNKdzMdX5i7HobCRdovekPdlh2YfCl3AKsm5ojuWBdGFj0owX5dYngCXwvVXW+tswe3TQe5BltfKdBEQEKd1pIDe0cftXTCKTgE68wtQKBgCXn/ilk88Z9zfq9PYfRIeJki+gulFXwwMGBk820ExAV/7wwqTOBrHTjKYqyP4k/P8+oeakn9uQN/KK/FtxTVlkpfGQDtljwTXcK6TH15IbYRPoBbP+xTDBHRtNqHWnf1LqN2xB2yBbYpaUQtv+UNDQ1YzhfcOZpcjlDwv+BdO9NAoGAXzA4qgD0czU54+MdxW6aT7TNJWq1Jwbb/QIEzvzgk92QhMYzCOuscCFNvLzKiEIUCyBmkMGyqmfXzM6+3CBATDa2pBa077g4EmO7/eAKgPX6grcup0PZeOEEuJiGdkb5nY4O3faZWWEFk295Ad8/8wmA1Tq8x7fvaPgokiQQg9U=
    access-token-expiration: PT1H
    id-token-expiration: PT1H
    refresh-token-expiration: PT24H
    jwe-enabled: true
  jws:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuSw55Oz/Q4GWJmnh5mJujvFwvoyPG5CBLEnRi2HzrBHMNtSt6avonGRo9x3GeOOEHSxh6k5pS2dMOdem0QMUwGzvr3ujgSi/om57qUG/OMAz5UMLXqOoLWRXVIxNE0Cu1nwFvdcxgOdEbYcfL2QmuLgIaGje/2DyfOsFc9HfdqQYr4gLQ39JeUeZ1u6noyOms/Q+jyoTLMbvDoA2U7dU0Bg+krefS7rS3SIPdRTfN96WnyNyuIa4edTOOWU8+VQCVh6CF8ahNkL/BRTLZLSPQlDhqyjA/MfuR2ZW2dGgbwjPxSVUC4ZTFIxVXYkt0GPIlLYL2hAT+1/6zONT+jsVVQIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5LDnk7P9DgZYmaeHmYm6O8XC+jI8bkIEsSdGLYfOsEcw21K3pq+icZGj3HcZ444QdLGHqTmlLZ0w516bRAxTAbO+ve6OBKL+ibnupQb84wDPlQwteo6gtZFdUjE0TQK7WfAW91zGA50Rthx8vZCa4uAhoaN7/YPJ86wVz0d92pBiviAtDf0l5R5nW7qejI6az9D6PKhMsxu8OgDZTt1TQGD6St59LutLdIg91FN833pafI3K4hrh51M45ZTz5VAJWHoIXxqE2Qv8FFMtktI9CUOGrKMD8x+5HZlbZ0aBvCM/FJVQLhlMUjFVdiS3QY8iUtgvaEBP7X/rM41P6OxVVAgMBAAECggEARA2Ga2VUPOWDnrN8I5TaR+tgwY7by0gUyQeKHL0PdhYGZMJN9hpJPyzBzMvjFKuc8rHMfHV7ygv5HirsslT9C+kdP3NjeETXBOWwydgRZFRy3heBNrNTy/bcB4UWkHRNrSLgY1ASb+rOoagupFacyndME78y8U0aYSFonBOuGiX9J2+pXKmECb4nlvFiWSQx/e9p1HcU6gc0J9q8RlNQKsPZlf8zgosPgRlG1Y5BtT9vpYSu8oNliE8fSFEPfnco9cbfrF0mseVJAHfc7xPAIhgWcy6j7IKl0FMARolfYiB7CUUkruRqX7k+/BcwdFXFeIzGYCqpIi/2X8+Rzpt+gwKBgQDryh4Wpudq7Ep9QWeBNAzjNjOxbF6rLTDJU8zdcQMILoHmcrF51XqRMmZ0O4VK49VC2aun0nV8Y4Wkzxu/ctC2V+4GVIGMsV6VBTKFwave+k1CR8kQ7ovSeU9hQ75KJ93tRMHTIPMvHEe8CLBIrVwUELyLwqG40BU9e4o0ul0VIwKBgQDJC29g23bCLKWvrM+DY0pddA3rvSWeljS83sf8qgO/7SGdcUR784FflHp8ASh85EdDK26NGyePXe9hHbaqhFJbeXVsIW6ozmwpMA9zZljKUtJAWQ681cuL0SRh52kub5nWTAeATKlfhYCQfs12m5BJjJYuKPfc8W2AF8yQx3X/JwKBgAUjPkyYDmrSAz1/c1XpYG6C+9Vd2yI3tdxtKwWYNMy01rfCwAM7l5QaWQknUtwy4q62N3tMpqqzMHJK4Pvm8I1IlTMmHDyIkNsGZfdsJOaS5aQQFF1+FSXc5tHju/25qKhG20JScXoRT67VMaIjxOHbC4CwGP4B6rSQQI6tkOGpAoGBAIPvxjM5M5GwfTdx4GkoQwhbfjtD0SlnB8sfJP1yka1lsJbDW59AqZmRNmSk2e5EXWP+X7mopWiXy93fAx6aYfX4GpBQzG9psF/DU5B3DTQR8DscduiEIeVq5kZ9+G/p+3pAQPf413qBgWLSZII/CwzJf1Fhv3A23Jagh7ZHv+8nAoGAXZJ+4/lmdDOnlgB6MHFsaAHqWYr/dS/3wwDSrWdRqkkNTUFwa/wetQ+l51bzjCf/71BKlUN48O3BzDRTX70DyK9QBu8wvXfljctClXcVSe10FbmE0I8ipHCTp7p7RbtRWos6tht2Y1UoXNHMpT/VqWjOXHvDxW4n4DQRa9Dne+A=
    jws-expiration: PT1H
  admin:
    username: admin
    password: password
    name: Admin User
    email: admin@example.com