server:
  port: 8071
spring:
  mvc:
    problemdetails:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o

management:
  tracing:
    enabled: false

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    io.github.susimsek.springaisamples: DEBUG
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  http:
    enabled: true
    level: FULL
    obfuscate:
      enabled: true
      mask-value: "****"
      headers:
        - Authorization
        - Cookie
        - Set-Cookie
        - X-API-Key
        - X-CSRF-Token
        - WWW-Authenticate
      parameters:
        - key
        - password
        - token
        - secret
        - api_key
        - access_token
        - refresh_token
      json-body-fields:
        - $.title
        - $.token
        - $.accessToken
        - $.refreshToken
        - $.idToken
        - $.email
        - $.secretKey
        - $.apiSecret
        - $.apiKey
    exclude:
      rules:
        - path-pattern: "/actuator/**"
        - pathPattern: "/error"
        - pathPattern: "/static/**"
        - pathPattern: "/public/**"
        - pathPattern: "/resources/**"
        - pathPattern: "/css/**"
        - pathPattern: "/js/**"
        - path-pattern: "/images/**"
        - path-pattern: "/favicon.ico"
        - pathPattern: "/webjars/**"
        - pathPattern: "/v3/api-docs/**"
        - pathPattern: "/swagger-ui/**"
    include:
      rules:
        - pathPattern: "/**"
weather:
  client:
    api-key: ${WEATHER_API_KEY}
    api-url: http://api.weatherapi.com/v1
