server:
  port: 8080
  forward-headers-strategy: framework
spring:
  application:
    name: spring-ai-samples
  main:
    allow-bean-definition-overriding: true
  output:
    ansi:
      enabled: always
  profiles:
    active: local
  web:
    locale: en
    resources:
      add-mappings: true
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
  mvc:
    problemdetails:
      enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    ratelimiters:
      enabled: true
    circuitbreakers:
      enabled: true
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: always
  info:
    env:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true


endpoints:
  shutdown:
    enabled: true

openapi:
  priority-tags:
    - security
    - auth
    - localization
    - ai
springdoc:
  swagger-ui:
    operationsSorter: method
    defaultModelsExpandDepth: -1
    display-request-duration: true
    filter: true
    show-extensions: true
    try-it-out-enabled: true
    persist-authorization: true

logging:
  level:
    ROOT: INFO
    io.github.susimsek.springaisamples: INFO
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'