version: '3.8'

services:
  web:
    image: suayb/spring-ai-samples:s17
    container_name: spring-ai-samples-api
    platform: linux/amd64
    ports:
      - "8071:8071"
    networks:
      - backend
    environment:
      SERVER_PORT: 8071
      SPRING_APPLICATION_NAME: spring-ai-samples
      SPRING_PROFILES_ACTIVE: default
      OPENAI_API_KEY: test
    healthcheck:
      test: curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  backend:
    driver: "bridge"